### ISSUE TITLE
Error: Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/api-plugin-files#20]
```terminal
==> typeDefault
api_1    |  image/jpeg jpg image/jpeg 
api_1    |  
api_1    | 11:35:02.082Z  INFO Reaction: After transformWrite file info is { name: 'WWuTm5nfvKx38A3yd.jpg', type: 'image/jpeg' }
api_1    | 11:35:02.083Z  INFO Reaction: S3Store _fileKeyMaker fileRecord info: { name: 'WWuTm5nfvKx38A3yd.jpg', type: 'image/jpeg' }
api_1    | 11:35:02.084Z  INFO Reaction: S3Store _fileKeyMaker fileRecord size: 38
api_1    | ReactionError: Error: Input buffer contains unsupported image format
api_1    |     at Sharp.<anonymous> (file:///usr/local/src/app/node_modules/api-plugin-files/src/utils/transformWrite.js:37:11)
api_1    |     at Sharp.emit (events.js:223:5)
api_1    |     at Sharp.EventEmitter.emit (domain.js:475:20)
api_1    |     at /usr/local/src/app/node_modules/sharp/lib/output.js:707:18 {
api_1    |   eventData: {},
api_1    |   error: 'error-sharp-resize-internal',
api_1    |   isClientSafe: true,
api_1    |   reason: [Error: Input buffer contains unsupported image format],
api_1    |   details: {}
api_1    | }
```
### The Solution is here
https://github.com/reactioncommerce/api-plugin-files/commit/0ca95a36464975abc0820c88f9d19f9efc053379

**Comment by MohanNarayana** [comment]
Issue is not reproducible.
