### ISSUE TITLE
GridStore is deprecated, and will be removed in a future version. Please use GridFSBucket instead

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/api-plugin-files#9]
```terminal
(node:75) DeprecationWarning: GridStore is deprecated, and will be removed in a future version. Please use GridFSBucket instead
api_1    | (node:75) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
api_1    | ReactionError: Error: Input buffer contains unsupported image format
api_1    |     at Sharp.<anonymous> (file:///usr/local/src/app/node_modules/api-plugin-files/src/setUpFileCollections.js:99:19)
api_1    |     at Sharp.emit (events.js:223:5)
api_1    |     at Sharp.EventEmitter.emit (domain.js:475:20)
api_1    |     at /usr/local/src/app/node_modules/sharp/lib/output.js:707:18 {
api_1    |   eventData: {},
api_1    |   error: 'error-sharp-resize-internal',
api_1    |   isClientSafe: true,
api_1    |   reason: [Error: Input buffer contains unsupported image format],
api_1    |   details: {}
api_1    | }
api_1    | 19:53:24.757Z  INFO Reaction: Stopping Reaction API...
api_1    | 19:53:24.758Z  INFO Reaction: Running shutdown function "jobQueueShutdown" for plugin "job-queue"...
api_1    | Failing 1 jobs on queue stop.
api_1    | 19:53:24.765Z  INFO Reaction: Shutdown function "jobQueueShutdown" for plugin "job-queue" finished in 6ms
api_1    | 19:53:24.775Z  INFO Reaction: Reaction API stopped
api_1    | [nodemon] app crashed - waiting for file changes before starting...
```

## Steps to Reproduce

1. Put A image in diroctory public
2. Save image by calling it through url by using fileRecord = await FileRecord.fromUrl(fileUrl, { fetch });

**Comment by delagroove** [comment]
not with the current bandwidth to update. if wanted please supply a PR.
